from .generated import Ability as Ability
from .generated import Area as Area
from .generated import CompetencyDescriptor as CompetencyDescriptor
from .generated import DescriptorRelations as DescriptorRelations
from .generated import Scope as Scope
from .generated import bundled_context as bundled_context
from .generated import constrained_by as constrained_by
from .generated import constrained_by_transitive as constrained_by_transitive
from .generated import constrains as constrains
from .generated import constrains_transitive as constrains_transitive
from .generated import contradicted_by as contradicted_by
from .generated import contradicted_by_transitive as contradicted_by_transitive
from .generated import contradicts as contradicts
from .generated import contradicts_transitive as contradicts_transitive
from .generated import deduct_admitting as deduct_admitting
from .generated import deduct_compatible as deduct_compatible
from .generated import definition as definition
from .generated import definitions as definitions
from .generated import expanded_by as expanded_by
from .generated import expanded_by_transitive as expanded_by_transitive
from .generated import expands as expands
from .generated import expands_transitive as expands_transitive
from .generated import has_part as has_part
from .generated import has_part_transitive as has_part_transitive
from .generated import implied_by as implied_by
from .generated import implied_by_transitive as implied_by_transitive
from .generated import implies as implies
from .generated import implies_transitive as implies_transitive
from .generated import incompatible as incompatible
from .generated import integrated_by as integrated_by
from .generated import integrated_by_transitive as integrated_by_transitive
from .generated import integrates as integrates
from .generated import integrates_transitive as integrates_transitive
from .generated import inverted_by as inverted_by
from .generated import inverted_by_transitive as inverted_by_transitive
from .generated import inverts as inverts
from .generated import inverts_transitive as inverts_transitive
from .generated import is_label_eligible as is_label_eligible
from .generated import part_of as part_of
from .generated import part_of_transitive as part_of_transitive
from .generated import relations as relations
from .generated import specialized_by as specialized_by
from .generated import specialized_by_transitive as specialized_by_transitive
from .generated import specializes as specializes
from .generated import specializes_transitive as specializes_transitive
from .generated import structured_by as structured_by
from .generated import structured_by_transitive as structured_by_transitive
from .generated import structures as structures
from .generated import structures_transitive as structures_transitive
from .generated import translated_by as translated_by
from .generated import translated_by_transitive as translated_by_transitive
from .generated import translates as translates
from .generated import translates_transitive as translates_transitive
